### ISSUE TITLE
Desktop

### ISSUE THREAD

**Issue by mikker** [DR-Nyheder-X/get-eu#12]
Lige nu er vi strictly mobile. What do with desktop?

**Comment by boetter** [comment]
Ja, vi skal finde en måde at bokse det ind på DR.dk desktop mode. Jeg synes ikke vi skal kaste særlig mange ressourcer efter det, bare at det virker på en måde der ikke er helt grim.

**Comment by boetter** [comment]
Jacques har vist fået nailet denne nu.
