### ISSUE TITLE
Topbar med DR navi og forsimplet lokal navi

### ISSUE THREAD

**Issue by boetter** [DR-Nyheder-X/get-eu#3]
DR top navi ala dette - og husk også footeren:

<img width="227" alt="screen shot 2015-10-19 at 11 11 40" src="https://cloud.githubusercontent.com/assets/1336222/10573770/3004876c-7652-11e5-934a-f2d8cbbcdf68.png">

Fjerne Lær/Test.

Gentænke visning af vores logo, point-antal og "menu" til reset af point, osv.

**Comment by mikker** [comment]
Jeg stemmer på, vi undgår footeren. Den er enorm, og giver ikke mening. Folk skal nok kunne finde tilbage, hvis de vil igen. No?

**Comment by boetter** [comment]
Lad os gøre det og så se om nogen bemærker det. Muligt vi bliver tvunget til at smide den på senere, men lad os bare rulle sådan her først.

**Comment by mikker** [comment]
:fire:
