### ISSUE TITLE
Bedre forklaring af hvorfor man får 50 point for at fuldføre afsnit

### ISSUE THREAD

**Issue by boetter** [DR-Nyheder-X/get-eu#37]
I designet har Jacques lavet det sådan at man får en forklaring af hvorfor man får 50 point hver gang man afslutter et afsnit, men den er vist glippet da vi kom over i koden. Kan vi hurtigt lige flette det ind igen?

**Comment by usr2323** [comment]
@mikker Hvis du kigger på dette screenshot, så kan du se det oprindelige bud på den forklarende tekst:
(Du skal selvfølgelig ignorere stylingen, som er outdated).
![cupcake5 2x](https://cloud.githubusercontent.com/assets/2797630/10965733/421cddea-83af-11e5-8a74-3abc8ed0ffe0.png)

10 points-tekst: "For at lære om..."
50 points-tekst: "For at lære alt om [category]"
