### ISSUE TITLE
Optimering inden launch

### ISSUE THREAD

**Issue by boetter** [DR-Nyheder-X/get-eu#8]
I ved selvfølgelig bedst selv hvad der skal gøres, så det er bare en reminder om at lave noget komprimering (måske gzip?) af ressourcer og html inden vi lancerer. PageSpeed mener der er 3,7 MB at spare på bundle.js?

**Comment by mikker** [comment]
Der er allerede en proces sat op. Det, du ser er dev-versionen, som er en hel del tungere end prod.

**Comment by boetter** [comment]
Det tænkte jeg nok - det var bare en reminder :)

**Comment by mikker** [comment]
:+1:

**Comment by mikker** [comment]
prod versionen er 645K. Stadig meget, men noget bedre.

**Comment by boetter** [comment]
Fedt!

**Comment by mikker** [comment]
Og det er altså både grafik + css + js.
